// Duty: single source of truth for DOM references.
// Query once, reuse everywhere.
export const elements = {
  langEn: document.getElementById("langEn"),
  langDe: document.getElementById("langDe"),
  downloadPdf: document.getElementById("downloadPdf"),
  contentRoot: document.getElementById("contentRoot"),
  sectionRail: document.getElementById("sectionRail"),
  sectionRailList: document.getElementById("sectionRailList"),
  sectionPanels: Array.from(document.querySelectorAll("[data-section-key]")),
  detailModalBackdrop: document.getElementById("detailModalBackdrop"),
  detailModalClose: document.getElementById("detailModalClose"),
  detailModalTitle: document.getElementById("detailModalTitle"),
  detailModalContent: document.getElementById("detailModalContent"),
  imageLightboxBackdrop: document.getElementById("imageLightboxBackdrop"),
  imageLightbox: document.getElementById("imageLightbox"),
  imageLightboxClose: document.getElementById("imageLightboxClose"),
  imageLightboxImg: document.getElementById("imageLightboxImg"),
  imageLightboxCaption: document.getElementById("imageLightboxCaption"),
  fullName: document.getElementById("fullName"),
  brandName: document.getElementById("brandName"),
  headline: document.getElementById("headline"),
  location: document.getElementById("location"),
  contactEmail: document.getElementById("contactEmail"),
  linkedin: document.getElementById("linkedin"),
  github: document.getElementById("github"),
  profilePhoto: document.getElementById("profilePhoto"),
  bioTitle: document.getElementById("bioTitle"),
  bioText: document.getElementById("bioText"),
  experienceTitle: document.getElementById("experienceTitle"),
  trainingsTitle: document.getElementById("trainingsTitle"),
  educationTitle: document.getElementById("educationTitle"),
  skillsTitle: document.getElementById("skillsTitle"),
  certTitle: document.getElementById("certTitle"),
  skillsList: document.getElementById("skillsList"),
  experienceList: document.getElementById("experienceList"),
  trainingsList: document.getElementById("trainingsList"),
  educationList: document.getElementById("educationList"),
  certGrid: document.getElementById("certGrid"),
  footerText: document.getElementById("footerText"),
};
